server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: admin-user-service
          uri: lb://user-service
          predicates:
            - Path=/api/admin/users/**
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/posts/**, /api/comments/**, /api/categories/**
        - id: admin-content-service
          uri: lb://forum-service
          predicates:
            - Path=/api/admin/posts/**, /api/admin/comments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/announcements/**, /api/reports/**, /api/admin/announcements/**, /api/admin/reports/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/upload/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
